pkg: Fix init script for mips

diff --git a/pkg/wheezy/init b/pkg/wheezy/init
--- a/pkg/wheezy/init
+++ b/pkg/wheezy/init
@@ -1,69 +1,78 @@
-#!/bin/bash
-#
-# Startup script for RTP Proxy
-#
-# chkconfig: 345 85 15
-# description: RTP Proxy is RTP proxy server to be used with SER
-#
-# processname: rtpproxy
-# pidfile: /var/run/rtpproxy.pid
+#! /bin/sh
+### BEGIN INIT INFO
+# Provides:          rtpproxy
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: RTP Proxy
+# Description:       Relay for VoIP media streams
+### END INIT INFO
 
-# Source function library.
-. /etc/rc.d/init.d/functions
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+NAME=rtpproxy
+DESC="RTP relay"
+DAEMON=/usr/bin/$NAME
+USER=root
+GROUP=root
+PIDFILE="/var/run/$NAME/$NAME.pid"
+PIDFILE_DIR=`dirname $PIDFILE`
+CONTROL_SOCK="unix:$PIDFILE_DIR/$NAME.sock"
 
-rtpproxy=/usr/local/sbin/rtpproxy
-prog=rtpproxy
-RETVAL=0
+test -x $DAEMON || exit 0
+umask 002
 
-start() {
-        echo -n $"Starting $prog: "
-        daemon $rtpproxy $OPTIONS
-        RETVAL=$?
-        echo
-        [ $RETVAL = 0 ] && touch /var/lock/subsys/rtpproxy
-        return $RETVAL
-}
+# Include defaults if available
+if [ -f /etc/default/$NAME ] ; then
+	. /etc/default/$NAME
+fi
 
-stop() {
-	echo -n $"Stopping $prog: "
-	killproc $rtpproxy
-	RETVAL=$?
-	echo
-	[ $RETVAL = 0 ] && rm -f /var/lock/subsys/rtpproxy /var/run/rtpproxy.pid
-}
+DAEMON_OPTS="-u $USER -f -p $PIDFILE -s $CONTROL_SOCK -l $AUDIO_SOCK -r $RECORDINGS_DIR $EXTRA_OPTS"
 
-reload() {
-	echo -n $"Reloading $prog: "
-	killproc $rtpproxy -HUP
-	RETVAL=$?
-	echo
-}
+if [ ! -d "$PIDFILE_DIR" ];then
+	mkdir "$PIDFILE_DIR"
+    chown $USER:$GROUP "$PIDFILE_DIR"
+fi
 
-# See how we were called.
+set -e
+
 case "$1" in
   start)
-	start
+	echo -n "Starting $DESC: "
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
+	echo "$NAME."
 	;;
   stop)
-	stop
+	echo -n "Stopping $DESC: "
+	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
+	echo "$NAME."
 	;;
   status)
-        status $rtpproxy
-	RETVAL=$?
-	;;
-  restart)
-	stop
-	start
-	;;
-  condrestart)
-	if [ -f /var/run/rtpproxy.pid ] ; then
-		stop
-		start
+	echo -n "Status $DESC: "
+	PID=$(cat $PIDFILE)
+	kill -0 $PID
+	rc=$?
+	# Check exit code
+	if [ "$rc" -ne 0 ]
+	then
+		echo "$NAME is NOT running."
+		exit 7
+	else
+		echo "$NAME is running with PID: $PID"
 	fi
 	;;
+  restart|force-reload)
+	echo -n "Restarting $DESC: "
+	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
+	sleep 1
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
+	echo "$NAME."
+	;;
   *)
-	echo $"Usage: $prog {start|stop|restart|condrestart|status|help}"
+	N=/etc/init.d/$NAME
+	echo "Usage: $N {start|stop|status|restart|force-reload}" >&2
 	exit 1
+	;;
 esac
 
-exit $RETVAL
+exit 0
